name: Publish

on:
  release:
    types: [published]

jobs:
  publish-platformio:
    name: Publish to PlatformIO
    runs-on: ubuntu-latest
    environment: platformio
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: '3.x'
      - name: Install platformio
        run: pip install --upgrade platformio
      - name: Publish package
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio package publish --owner improv --non-interactive

  publish-espressif:
    name: Publish to Espressif
    runs-on: ubuntu-latest
    environment: espressif
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - name: Publish package
        uses: espressif/upload-components-ci-action@355b0bb4d41e94edbec03d08c0ba0c11bbc4834d  # v2
        with:
          version: ${{ github.event.release.tag_name }}
          components: |
            improv: .
          namespace: improv
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
