name: Publish

on:
  release:
    types: [published]

jobs:
  publish-platformio:
    name: Publish to PlatformIO
    runs-on: ubuntu-latest
    environment: platformio
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: '3.x'
      - name: Install platformio
        run: pip install --upgrade platformio
      - name: Publish package
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio package publish --owner improv --non-interactive

  publish-espressif:
    name: Publish to Espressif
    runs-on: ubuntu-latest
    environment: espressif
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Publish package
        uses: espressif/upload-components-ci-action@2ce17d73e35473317c1419dbd4f007aacb593040  # v2.2.1
        with:
          version: ${{ github.event.release.tag_name }}
          components: |
            improv: .
          namespace: improv
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
