name: Publish

on:
  release:
    types: [published]

jobs:
  publish-platformio:
    name: Publish to PlatformIO
    runs-on: ubuntu-latest
    environment: platformio
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.x'
      - name: Install platformio
        run: pip install --upgrade platformio
      - name: Publish package
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio package publish --owner improv --non-interactive

  publish-espressif:
    name: Publish to Espressif
    runs-on: ubuntu-latest
    environment: espressif
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Publish package
        uses: espressif/upload-components-ci-action@2ce17d73e35473317c1419dbd4f007aacb593040  # v2.2.1
        with:
          version: ${{ github.event.release.tag_name }}
          components: |
            improv: .
          namespace: improv
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
